"""Add unique constraint on ShareHistory

Revision ID: 701c8cda5915
Revises: 2dfb8ce079e5
Create Date: 2023-12-25 22:10:11.651792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701c8cda5915'
down_revision: Union[str, None] = '2dfb8ce079e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_share_id_date', 'share_history', ['share_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_share_id_date', 'share_history', type_='unique')
    # ### end Alembic commands ###
