"""Added unique constraint share actions

Revision ID: 964908c0a7bd
Revises: c23ec10e8cd3
Create Date: 2024-01-18 21:14:04.941078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964908c0a7bd'
down_revision: Union[str, None] = 'c23ec10e8cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_purchase_date_share_id_isin_description_order_id', 'share_actions', ['purchase_date', 'share_id', 'isin', 'action', 'order_id'])
    op.drop_column('share_actions', 'testCol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_actions', sa.Column('testCol', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_purchase_date_share_id_isin_description_order_id', 'share_actions', type_='unique')
    # ### end Alembic commands ###
