"""Added unique constraint

Revision ID: c23ec10e8cd3
Revises: 52c1139f99e2
Create Date: 2024-01-18 20:37:22.415099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23ec10e8cd3'
down_revision: Union[str, None] = '52c1139f99e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_isin', 'share_info', ['isin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_isin', 'share_info', type_='unique')
    # ### end Alembic commands ###
