"""Create a baseline migrations

Revision ID: ef227d66b2c3
Revises: 
Create Date: 2023-12-23 20:57:26.549340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef227d66b2c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.VARCHAR(length=256), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('share_actions',
    sa.Column('id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('share_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('currency_date', sa.Date(), nullable=True),
    sa.Column('product', sa.VARCHAR(length=500), nullable=True),
    sa.Column('fxrate', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('isin', sa.VARCHAR(length=256), nullable=True),
    sa.Column('mutation_currency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mutation', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('order_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('action', sa.Numeric(), nullable=True),
    sa.Column('hash', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('share_price', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('testCol', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('share_history',
    sa.Column('id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('share_id', sa.VARCHAR(length=256), nullable=True),
    sa.Column('open', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('volume', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('dividends', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('stock_splits', sa.DECIMAL(precision=19, scale=4), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('share_info',
    sa.Column('id', sa.VARCHAR(length=256), nullable=False),
    sa.Column('isin', sa.VARCHAR(length=256), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('market', sa.VARCHAR(length=256), nullable=True),
    sa.Column('ticker', sa.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('share_info')
    op.drop_table('share_history')
    op.drop_table('share_actions')
    op.drop_table('config')
    # ### end Alembic commands ###
