"""Add capital gains

Revision ID: efd992ae5249
Revises: 701c8cda5915
Create Date: 2024-01-07 11:53:11.703497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd992ae5249'
down_revision: Union[str, None] = '701c8cda5915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('share_history', sa.Column('capital_gains', sa.DECIMAL(precision=19, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_history', 'capital_gains')
    # ### end Alembic commands ###
